# Generated by Django 3.2.8 on 2021-10-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_remove_food_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='offer',
        ),
    ]
